// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "graphView.enable": boolean;
      "graphView.mode": string;
      "graphView.scope": string;
      "graphView.theme": string;
      "graphView.nodeCap": number;
      "graphView.showLabels": boolean;
      "graphView.charge": number;
      "graphView.linkDistance": number;
    };
  }
}
