// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "hub.lastView": string;
      "hub.defaultView": string;
      "hub.theme": string;
      "hub.topN": number;
      "hub.networkCap": number;
      "insights.source": string;
      "insights.dockHeight": number;
      "insights.maximized": boolean;
    };
  }
}
